import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
MatButtonModule,
MatProgressBarModule,
MatDividerModule,
MatCheckboxModule,
MatRadioModule,
MatInputModule,
MatSelectModule,
MatGridListModule,
MatListModule,
MatBadgeModule,
MatSliderModule,
MatSlideToggleModule,
MatMenuModule,
MatToolbarModule,
MatIconModule,
MatSidenavModule,
MatCardModule,
MatExpansionModule,
MatAutocompleteModule,
MatNativeDateModule,
MatDatepickerModule,
MatChipsModule,
MatBottomSheetModule,
MatStepperModule,
MatSnackBarModule,
MatProgressSpinnerModule,
MatTabsModule,
MatPaginatorModule,
MatButtonToggleModule,
MatTooltipModule,
MatTreeModule
} from '@angular/material';
@NgModule({
  exports: [
    CommonModule,
    MatDatepickerModule,
    MatButtonModule, 
    MatCheckboxModule,
    MatRadioModule,
    MatBadgeModule,
    MatChipsModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatInputModule,
    MatDividerModule,
    MatListModule,
    MatNativeDateModule,
    MatSnackBarModule,
    MatPaginatorModule,
    MatSelectModule,
    MatBottomSheetModule,
    MatSliderModule,
    MatGridListModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatIconModule,
    MatSidenavModule,
    MatStepperModule,
    MatProgressSpinnerModule,
    MatCardModule,
    MatExpansionModule,
    MatToolbarModule,
    MatTabsModule,
    MatButtonToggleModule,
    MatTooltipModule,
    MatTreeModule

  ]
})
export class MatModuleModule { }
